name: mqtt

services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    networks:
      - smart-springfield-server_default
    ports:
      - "1883:1883"
    tmpfs:
      - /mosquitto/data
      - /mosquitto/log

networks:
  smart-springfield-server_default:
    external: true
