[[inputs.system]]
[[inputs.mqtt_consumer]]
servers = ["tcp://mosquitto:1883"]

topics = [
  "sensors/#"
]

[[outputs.file]]

[[outputs.influxdb_v3]]
  urls = ["http://influxdb3-core:8181"]

  ## Token for authentication
  token = "${TOKEN}"

  ## Destination database to write into
  database = "mydb"
